document.addEventListener("DOMContentLoaded", () => {
  const audio = document.getElementById("audio");
  const playPauseBtn = document.getElementById("play-pause");
  const prevBtn = document.getElementById("prev");
  const nextBtn = document.getElementById("next");
  const trackTitle = document.getElementById("track-title");
  const minimizeBtn = document.getElementById("minimize-btn");
  const player = document.getElementById("music-player");
  const queueDiv = document.getElementById("music-queue");

  // Playlist (auto-generated by download_songs.py)
  const playlist = [
    { title: "Taylor Swift - Alchemy", src: "playlist/Taylor Swift - The Alchemy (Official Lyric Video).mp3" },
    { title: "Taylor Swift - Paper Rings", src: "playlist/Taylor Swift - Paper Rings (Official Audio).mp3" },
    { title: "Taylor Swift - Anti-Hero", src: "playlist/Taylor Swift - Anti-Hero (Official Lyric Video).mp3" },
    { title: "Taylor Swift - Cruel Summer", src: "playlist/Taylor Swift - Cruel Summer (Official Audio).mp3" },
    { title: "Ado - Vivarium", src: "playlist/【Ado】ビバリウム (Vivarium).mp3" },
    { title: "Vaundy - Odoriko", src: "playlist/【第75回NHK紅白歌合戦 歌唱曲】踊り子 ⧸ Vaundy：MUSIC VIDEO.mp3" },
    { title: "Eve - Heikousen", src: "playlist/平行線 - Eve × suis from ヨルシカ MV.mp3" },
   
    
  ];

  let currentTrack = 0;

  function loadTrack(index) {
    const track = playlist[index];
    audio.src = track.src;
    trackTitle.textContent = `Now Playing: ${track.title}`;
    audio.load();
    // For accessibility: update document title
    document.title = `Now Playing: ${track.title}`;
    renderQueue();
  }

  function renderQueue() {
    if (!queueDiv) return;
    if (player.classList.contains("collapsed")) {
      queueDiv.style.display = "none";
      return;
    }
    let html = '<ul style="list-style:none;padding:0;margin:8px 0 0 0;max-height:120px;overflow-y:auto;font-size:0.95em;">';
    playlist.forEach((track, i) => {
      if (i === currentTrack) {
        html += `<li style='color:#ff80ab;font-weight:bold;'>▶ ${track.title}</li>`;
      } else {
        html += `<li style='color:#6b6bff;'>${track.title}</li>`;
      }
    });
    html += '</ul>';
    queueDiv.innerHTML = html;
    queueDiv.style.display = "block";
  }

  playPauseBtn.addEventListener("click", () => {
    const icon = playPauseBtn.querySelector(".material-icons");
    if (audio.paused) {
      audio.play();
      icon.textContent = "pause_circle";
    } else {
      audio.pause();
      icon.textContent = "play_circle";
    }
    playPauseBtn.blur();
  });

  prevBtn.addEventListener("click", () => {
    currentTrack = (currentTrack - 1 + playlist.length) % playlist.length;
    loadTrack(currentTrack);
    audio.play();
    const icon = playPauseBtn.querySelector(".material-icons");
    icon.textContent = "pause_circle";
    prevBtn.blur();
  });

  nextBtn.addEventListener("click", () => {
    currentTrack = (currentTrack + 1) % playlist.length;
    loadTrack(currentTrack);
    audio.play();
    const icon = playPauseBtn.querySelector(".material-icons");
    icon.textContent = "pause_circle";
    nextBtn.blur();
  });

  audio.addEventListener("ended", () => {
    currentTrack = (currentTrack + 1) % playlist.length;
    loadTrack(currentTrack);
    audio.play();
  });

  minimizeBtn.addEventListener("click", () => {
    player.classList.toggle("collapsed");
    minimizeBtn.blur();
    renderQueue();
  });

  loadTrack(currentTrack);
  renderQueue();
  // Keyboard accessibility: space/enter for controls
  [playPauseBtn, prevBtn, nextBtn, minimizeBtn].forEach(btn => {
    btn.addEventListener('keyup', (e) => {
      if (e.key === ' ' || e.key === 'Enter') {
        btn.click();
      }
    });
  });
});
